<a href="https://colab.research.google.com/github/kirat-anand-68/NEURAL_NETWORKS/blob/main/KRISH_NAIK.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# braek down the neural network
# x-> input
# wx-> weights
# bx -> bias
# A-> Activation function
# y-> output.

# Z=W1.X + b1
# Z' =A(Z)
# Y=W2.Z' + b2

# loss function->
# backpropagation
# Optimizer

In [ ]:
# components of pytorch
# base class for defining custom models is : torch.nn.Module
# fuly connected or dense layers : torch.nn.Linear
# Activation function : torch.nn.ReLU
# Optimizer : torch.optim
# Loss : torch.nn.CrossEntropyLoss
# loads data in batches : torch.utils.data.DataLoader

In [ ]:
# #Ways to create a Neural Network
# Function : torch.nn.Function  more flexible, harder to interpret
# Sequential : nn.Sequential

In [1]:
# BUILDING A NEURAL NETWORK
import torch
import torch.nn as nn
import torch.optim as optim

In [2]:
# Functional API
class SimpleNN(nn.Module):

  def __init__(self, input_size,hidden_size, output_size):
    super(SimpleNN, self).__init__()

    self.fc1 = nn.Linear(input_size, hidden_size)

    self.relu = nn.ReLU()

    self.fc2 = nn.Linear(hidden_size, output_size)

  def forward(self, x):
    x=self.fc1(x)
    x=self.relu(x)
    x=self.fc2(x)
    return x

In [3]:
# sequential API
class SimpleNNSequential(nn.Module):

  def __init__(self, input_size,hidden_size, output_size):
    super(SimpleNNSequential, self).__init__()

    self.network=nn.Sequential(
        nn.Linear(input_size, hidden_size),
        nn.ReLU(),
        nn.Linear(hidden_size, output_size)

    )
  def forward(self, x):
    return self.network(x)

In [4]:
# training the neural network

model=SimpleNN(input_size=4, hidden_size=8, output_size=3)
print(model)

SimpleNN(
  (fc1): Linear(in_features=4, out_features=8, bias=True)
  (relu): ReLU()
  (fc2): Linear(in_features=8, out_features=3, bias=True)
)

In [6]:
X=torch.randn(10,4) # 10 samples

Y=torch.randint(0,3,(10,))

criteiro=nn.CrossEntropyLoss()
optimizer= optim.Adam(model.parameters(), lr=0.01)

In [7]:
print(X)

tensor([[ 0.4586, -0.0781,  0.6407,  0.3526],
        [-0.6280,  0.5917,  2.3621, -0.7249],
        [ 0.1585,  1.7706,  2.1152,  0.6860],
        [-0.5852,  0.0091, -1.2536, -0.3923],
        [-0.1382, -1.6360,  0.0842, -0.8433],
        [-0.5379, -0.6840,  1.5249,  0.6302],
        [ 0.6630, -0.5720,  0.3439, -1.0380],
        [ 0.6694,  1.5868, -0.8891, -0.5509],
        [ 0.1601,  0.4395,  0.9788, -0.4517],
        [ 1.1332, -1.4969,  1.5285, -0.0426]])

In [9]:
print(Y)

tensor([0, 2, 1, 0, 2, 2, 1, 2, 0, 1])

In [13]:
# training loop
epochs=50
for e in range(epochs):
  optimizer.zero_grad()
  outputs=model.forward(X)
  loss=criteiro(outputs, Y)
  loss.backward()
  optimizer.step()

  if (e+1) % 10 == 0:
    print(f"EPOCH [{e+1}]/50, Loss :{loss.item():.4f}")

EPOCH [10]/50, Loss :0.9235
EPOCH [20]/50, Loss :0.7813
EPOCH [30]/50, Loss :0.6381
EPOCH [40]/50, Loss :0.5027
EPOCH [50]/50, Loss :0.3884

In [ ]:
# REGRESSION MODEL USING THE PYTORCH
# Data gathering
# Data preprocessing
# Feature Engineering
# Model trained
# testing the model on the test set

In [14]:
import torch
import torch.nn as nn
import torch.optim as optim

# Model
model = nn.Sequential(
    nn.Linear(4, 8),
    nn.ReLU(),
    nn.Linear(8, 3)
)

# Dummy data
X = torch.randn(10, 4)
Y = torch.randint(0, 3, (10,))

# Loss and optimizer
criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=0.01)

# Training
for epoch in range(50):

    # Forward pass
    outputs = model(X)

    # Calculate loss
    loss = criterion(outputs, Y)

    # Backpropagation
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    # Print loss
    if (epoch + 1) % 10 == 0:
        print(f" Epoch {epoch+1}, Loss: {loss.item():.4f }")

Epoch 10, Loss: 0.8830
Epoch 20, Loss: 0.7523
Epoch 30, Loss: 0.6519
Epoch 40, Loss: 0.5608
Epoch 50, Loss: 0.5056

In [16]:
import pandas as pd

In [25]:
df=pd.read_csv("helloonsaurance.csv")

In [26]:
df.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1338 non-null   int64
 1   sex       1338 non-null   object
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64
 4   smoker    1338 non-null   object
 5   region    1338 non-null   object
 6   charges   1338 non-null   float64
dtypes: float64(2), int64(2), object(3)
memory usage: 73.3+ KB

In [28]:
df.isnull().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

In [29]:
! pip install kaggle

Requirement already satisfied: kaggle in /usr/local/lib/python3.12/dist-packages (2.0.2)
Requirement already satisfied: bleach in /usr/local/lib/python3.12/dist-packages (from kaggle) (6.3.0)
Requirement already satisfied: jupytext in /usr/local/lib/python3.12/dist-packages (from kaggle) (1.19.1)
Requirement already satisfied: kagglesdk<1.0,>=0.1.20 in /usr/local/lib/python3.12/dist-packages (from kaggle) (0.1.20)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from kaggle) (26.1)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from kaggle) (5.29.6)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.12/dist-packages (from kaggle) (2.9.0.post0)
Requirement already satisfied: python-slugify in /usr/local/lib/python3.12/dist-packages (from kaggle) (8.0.4)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from kaggle) (2.32.4)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from kaggle) (4.67.3)
Requirement already satisfied: urllib3>=1.15.1 in /usr/local/lib/python3.12/dist-packages (from kaggle) (2.5.0)
Requirement already satisfied: webencodings in /usr/local/lib/python3.12/dist-packages (from bleach->kaggle) (0.5.1)
Requirement already satisfied: markdown-it-py>=1.0 in /usr/local/lib/python3.12/dist-packages (from jupytext->kaggle) (4.0.0)
Requirement already satisfied: mdit-py-plugins in /usr/local/lib/python3.12/dist-packages (from jupytext->kaggle) (0.5.0)
Requirement already satisfied: nbformat in /usr/local/lib/python3.12/dist-packages (from jupytext->kaggle) (5.10.4)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.12/dist-packages (from jupytext->kaggle) (6.0.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil->kaggle) (1.17.0)
Requirement already satisfied: text-unidecode>=1.3 in /usr/local/lib/python3.12/dist-packages (from python-slugify->kaggle) (1.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->kaggle) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->kaggle) (3.13)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->kaggle) (2026.4.22)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=1.0->jupytext->kaggle) (0.1.2)
Requirement already satisfied: fastjsonschema>=2.15 in /usr/local/lib/python3.12/dist-packages (from nbformat->jupytext->kaggle) (2.21.2)
Requirement already satisfied: jsonschema>=2.6 in /usr/local/lib/python3.12/dist-packages (from nbformat->jupytext->kaggle) (4.26.0)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in /usr/local/lib/python3.12/dist-packages (from nbformat->jupytext->kaggle) (5.9.1)
Requirement already satisfied: traitlets>=5.1 in /usr/local/lib/python3.12/dist-packages (from nbformat->jupytext->kaggle) (5.7.1)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=2.6->nbformat->jupytext->kaggle) (0.30.0)
Requirement already satisfied: platformdirs>=2.5 in /usr/local/lib/python3.12/dist-packages (from jupyter-core!=5.0.*,>=4.12->nbformat->jupytext->kaggle) (4.9.6)
Requirement already satisfied: typing-extensions>=4.4.0 in /usr/local/lib/python3.12/dist-packages (from referencing>=0.28.4->jsonschema>=2.6->nbformat->jupytext->kaggle) (4.15.0)

In [ ]:
# path=kagglehub.dataset_download(" ")
# print(path)

In [30]:
df.describe()

               age          bmi     children       charges
count  1338.000000  1338.000000  1338.000000   1338.000000
mean     39.207025    30.663397     1.094918  13270.422265
std      14.049960     6.098187     1.205493  12110.011237
min      18.000000    15.960000     0.000000   1121.873900
25%      27.000000    26.296250     0.000000   4740.287150
50%      39.000000    30.400000     1.000000   9382.033000
75%      51.000000    34.693750     2.000000  16639.912515
max      64.000000    53.130000     5.000000  63770.428010

In [31]:
df["age"].value_counts()

age
18    69
19    68
46    29
52    29
50    29
47    29
48    29
51    29
45    29
20    29
24    28
27    28
28    28
25    28
23    28
49    28
54    28
53    28
22    28
21    28
26    28
31    27
41    27
44    27
43    27
42    27
29    27
30    27
40    27
32    26
33    26
57    26
34    26
55    26
56    26
35    25
58    25
37    25
59    25
39    25
36    25
38    25
62    23
60    23
63    23
61    23
64    22
Name: count, dtype: int64

In [32]:
import torch
import torch.nn as nn
import torch.optim as optim
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.model_selection import train_test_split

In [33]:
# split the dataset before encoder
train_df, test_df = train_test_split(df,test_size=0.2, random_state=42)

In [34]:
# Encode categorical variables
label_encoder = {}
for col in ['sex','smoker','region']:
  le=LabelEncoder()
  train_df[col]=le.fit_transform(train_df[col])
  test_df[col]=le.transform(test_df[col])
  label_encoder[col] = le

In [36]:
# features and target
X_train=train_df.drop(columns=['charges'])
Y_train=train_df['charges']

X_test=test_df.drop(columns=['charges'])
Y_test=test_df['charges']

In [37]:
print(X_train)

      age  sex     bmi  children  smoker  region
560    46    0  19.950         2       0       1
1285   47    0  24.320         0       0       0
1142   52    0  24.860         0       0       2
969    39    0  34.320         5       0       2
486    54    0  21.470         3       0       1
...   ...  ...     ...       ...     ...     ...
1095   18    0  31.350         4       0       0
1130   39    0  23.870         5       0       2
1294   58    1  25.175         0       0       0
860    37    0  47.600         2       1       3
1126   55    1  29.900         0       0       3

[1070 rows x 6 columns]

In [38]:
print(Y_train)

560      9193.83850
1285     8534.67180
1142    27117.99378
969      8596.82780
486     12475.35130
           ...
1095     4561.18850
1130     8582.30230
1294    11931.12525
860     46113.51100
1126    10214.63600
Name: charges, Length: 1070, dtype: float64

In [39]:
# Normalize features
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.fit_transform(X_test)

In [40]:
print(X_train)

[[ 0.47222651 -1.0246016  -1.75652513  0.73433626 -0.50874702 -0.45611589]
 [ 0.54331294 -1.0246016  -1.03308239 -0.91119211 -0.50874702 -1.35325561]
 [ 0.8987451  -1.0246016  -0.94368672 -0.91119211 -0.50874702  0.44102382]
 ...
 [ 1.3252637   0.97598911 -0.89153925 -0.91119211 -0.50874702 -1.35325561]
 [-0.16755139 -1.0246016   2.82086429  0.73433626  1.96561348  1.33816354]
 [ 1.1120044   0.97598911 -0.10932713 -0.91119211 -0.50874702  1.33816354]]

In [41]:
print(Y_train)

560      9193.83850
1285     8534.67180
1142    27117.99378
969      8596.82780
486     12475.35130
           ...
1095     4561.18850
1130     8582.30230
1294    11931.12525
860     46113.51100
1126    10214.63600
Name: charges, Length: 1070, dtype: float64

In [43]:
# convert to tensors
X_train_tensor=torch.tensor(X_train, dtype=torch.float32)
Y_train_tensor=torch.tensor(Y_train.values, dtype=torch.float32).view(-1,1)
X_test_tensor=torch.tensor(X_test, dtype=torch.float32)
Y_test_tensor=torch.tensor(Y_test.values, dtype=torch.float32).view(-1,1)

In [45]:
print(Y_train_tensor)

tensor([[ 9193.8389],
        [ 8534.6719],
        [27117.9941],
        ...,
        [11931.1250],
        [46113.5117],
        [10214.6357]])

In [46]:
print(X_test_tensor)

tensor([[ 0.4586, -0.9562, -0.9372,  0.8225, -0.5023, -1.4541],
        [-0.1871, -0.9562, -0.1675, -0.8996, -0.5023, -0.5128],
        [ 1.8218, -0.9562, -0.6655, -0.8996,  1.9907, -0.5128],
        ...,
        [-0.0436,  1.0458, -0.4844, -0.0386, -0.5023, -1.4541],
        [ 1.1043, -0.9562,  2.5949, -0.8996,  1.9907,  0.4285],
        [ 0.8891, -0.9562,  0.4965, -0.0386, -0.5023,  1.3698]])

In [50]:
# Define Neural Network Model

class SimpleNNRegressionModel(nn.Module):
  def __init__(self, input_dim):
    super(SimpleNNRegressionModel, self).__init__()
    self.network = nn.Sequential(
        nn.Linear(input_dim, 64),
        nn.ReLU(),
        nn.Linear(64, 128),
        nn.ReLU(),
        nn.Linear(128, 1)
    )

  def forward(self, x):
    return self.network(x)

In [48]:
X_train_tensor.shape

torch.Size([1070, 6])

In [52]:
input_dim = X_train_tensor.shape[1]

model = SimpleNNRegressionModel(input_dim)

In [53]:
print(model)

SimpleNNRegressionModel(
  (network): Sequential(
    (0): Linear(in_features=6, out_features=64, bias=True)
    (1): ReLU()
    (2): Linear(in_features=64, out_features=128, bias=True)
    (3): ReLU()
    (4): Linear(in_features=128, out_features=1, bias=True)
  )
)

In [59]:
# loss and optiizer

criterion = nn.MSELoss()

optimizer = optim.Adam(model.parameters(), lr=0.01)

epochs = 30000

for epoch in range(epochs):

    model.train()

    optimizer.zero_grad()

    prediction = model(X_train_tensor)

    loss = criterion(prediction, Y_train_tensor)

    loss.backward()

    optimizer.step()

    if (epoch + 1) % 100 == 0:
        print(f"Epoch [{epoch+1}/{epochs}], Loss: {loss.item():.6f}")

Epoch [100/30000], Loss: 1427134.000000
Epoch [200/30000], Loss: 1422443.375000
Epoch [300/30000], Loss: 1421724.750000
Epoch [400/30000], Loss: 1421169.875000
Epoch [500/30000], Loss: 1420535.250000
Epoch [600/30000], Loss: 1420076.125000
Epoch [700/30000], Loss: 1419175.000000
Epoch [800/30000], Loss: 1418725.250000
Epoch [900/30000], Loss: 1417786.875000
Epoch [1000/30000], Loss: 1416907.500000
Epoch [1100/30000], Loss: 1416418.375000
Epoch [1200/30000], Loss: 1415314.375000
Epoch [1300/30000], Loss: 1414091.125000
Epoch [1400/30000], Loss: 1413096.125000
Epoch [1500/30000], Loss: 1411826.375000
Epoch [1600/30000], Loss: 1411688.375000
Epoch [1700/30000], Loss: 1413825.125000
Epoch [1800/30000], Loss: 1427042.750000
Epoch [1900/30000], Loss: 1412491.375000
Epoch [2000/30000], Loss: 1454151.625000
Epoch [2100/30000], Loss: 1458984.000000
Epoch [2200/30000], Loss: 1406733.000000
Epoch [2300/30000], Loss: 1430993.375000
Epoch [2400/30000], Loss: 1428673.750000
Epoch [2500/30000], Loss: 1411202.375000
Epoch [2600/30000], Loss: 1442580.625000
Epoch [2700/30000], Loss: 1438451.625000
Epoch [2800/30000], Loss: 1398691.625000
Epoch [2900/30000], Loss: 1451406.125000
Epoch [3000/30000], Loss: 1429192.125000
Epoch [3100/30000], Loss: 1451161.375000
Epoch [3200/30000], Loss: 1402662.625000
Epoch [3300/30000], Loss: 1439390.500000
Epoch [3400/30000], Loss: 1419714.625000
Epoch [3500/30000], Loss: 1396444.625000
Epoch [3600/30000], Loss: 1445061.250000
Epoch [3700/30000], Loss: 1419979.500000
Epoch [3800/30000], Loss: 1386955.750000
Epoch [3900/30000], Loss: 1403309.125000
Epoch [4000/30000], Loss: 1380603.500000
Epoch [4100/30000], Loss: 1401631.625000
Epoch [4200/30000], Loss: 1401215.875000
Epoch [4300/30000], Loss: 1380470.500000
Epoch [4400/30000], Loss: 1411327.000000
Epoch [4500/30000], Loss: 1404728.375000
Epoch [4600/30000], Loss: 1429381.250000
Epoch [4700/30000], Loss: 1375037.875000
Epoch [4800/30000], Loss: 1374429.250000
Epoch [4900/30000], Loss: 1387816.375000
Epoch [5000/30000], Loss: 1401708.875000
Epoch [5100/30000], Loss: 1371921.625000
Epoch [5200/30000], Loss: 1391705.125000
Epoch [5300/30000], Loss: 1392188.750000
Epoch [5400/30000], Loss: 1365196.750000
Epoch [5500/30000], Loss: 1425117.250000
Epoch [5600/30000], Loss: 1387516.750000
Epoch [5700/30000], Loss: 1356480.500000
Epoch [5800/30000], Loss: 1387363.500000
Epoch [5900/30000], Loss: 1358125.875000
Epoch [6000/30000], Loss: 1396921.625000
Epoch [6100/30000], Loss: 1376996.500000
Epoch [6200/30000], Loss: 1404665.500000
Epoch [6300/30000], Loss: 1410644.750000
Epoch [6400/30000], Loss: 1396431.125000
Epoch [6500/30000], Loss: 1359020.375000
Epoch [6600/30000], Loss: 1396361.125000
Epoch [6700/30000], Loss: 1422312.875000
Epoch [6800/30000], Loss: 1348519.125000
Epoch [6900/30000], Loss: 1397515.500000
Epoch [7000/30000], Loss: 1391210.500000
Epoch [7100/30000], Loss: 1338300.500000
Epoch [7200/30000], Loss: 1343654.000000
Epoch [7300/30000], Loss: 1392022.500000
Epoch [7400/30000], Loss: 1379556.750000
Epoch [7500/30000], Loss: 1335084.500000
Epoch [7600/30000], Loss: 1360629.500000
Epoch [7700/30000], Loss: 1372926.500000
Epoch [7800/30000], Loss: 1374994.000000
Epoch [7900/30000], Loss: 1327153.250000
Epoch [8000/30000], Loss: 1359154.250000
Epoch [8100/30000], Loss: 1385002.875000
Epoch [8200/30000], Loss: 1328305.000000
Epoch [8300/30000], Loss: 1392418.375000
Epoch [8400/30000], Loss: 1330583.500000
Epoch [8500/30000], Loss: 1395741.125000
Epoch [8600/30000], Loss: 1322144.875000
Epoch [8700/30000], Loss: 1348469.875000
Epoch [8800/30000], Loss: 1316090.875000
Epoch [8900/30000], Loss: 1376190.875000
Epoch [9000/30000], Loss: 1330683.125000
Epoch [9100/30000], Loss: 1344620.625000
Epoch [9200/30000], Loss: 1325199.500000
Epoch [9300/30000], Loss: 1326565.250000
Epoch [9400/30000], Loss: 1373648.750000
Epoch [9500/30000], Loss: 1316552.125000
Epoch [9600/30000], Loss: 1312136.625000
Epoch [9700/30000], Loss: 1310377.875000
Epoch [9800/30000], Loss: 1334752.625000
Epoch [9900/30000], Loss: 1350730.875000
Epoch [10000/30000], Loss: 1303283.000000
Epoch [10100/30000], Loss: 1355836.000000
Epoch [10200/30000], Loss: 1311985.500000
Epoch [10300/30000], Loss: 1322031.875000
Epoch [10400/30000], Loss: 1348007.875000
Epoch [10500/30000], Loss: 1296663.125000
Epoch [10600/30000], Loss: 1317221.750000
Epoch [10700/30000], Loss: 1360458.250000
Epoch [10800/30000], Loss: 1316808.250000
Epoch [10900/30000], Loss: 1310765.625000
Epoch [11000/30000], Loss: 1374166.500000
Epoch [11100/30000], Loss: 1289612.000000
Epoch [11200/30000], Loss: 1318576.625000
Epoch [11300/30000], Loss: 1337081.875000
Epoch [11400/30000], Loss: 1317938.375000
Epoch [11500/30000], Loss: 1281437.250000
Epoch [11600/30000], Loss: 1289707.750000
Epoch [11700/30000], Loss: 1307325.000000
Epoch [11800/30000], Loss: 1288621.625000
Epoch [11900/30000], Loss: 1311443.000000
Epoch [12000/30000], Loss: 1289376.000000
Epoch [12100/30000], Loss: 1311299.250000
Epoch [12200/30000], Loss: 1332987.625000
Epoch [12300/30000], Loss: 1273487.250000
Epoch [12400/30000], Loss: 1294663.750000
Epoch [12500/30000], Loss: 1289512.250000
Epoch [12600/30000], Loss: 1315956.000000
Epoch [12700/30000], Loss: 1284394.500000
Epoch [12800/30000], Loss: 1272333.375000
Epoch [12900/30000], Loss: 1301520.875000
Epoch [13000/30000], Loss: 1323602.125000
Epoch [13100/30000], Loss: 1266033.000000
Epoch [13200/30000], Loss: 1306071.125000
Epoch [13300/30000], Loss: 1346428.625000
Epoch [13400/30000], Loss: 1266634.875000
Epoch [13500/30000], Loss: 1319481.125000
Epoch [13600/30000], Loss: 1293241.125000
Epoch [13700/30000], Loss: 1260627.750000
Epoch [13800/30000], Loss: 1291977.375000
Epoch [13900/30000], Loss: 1260303.250000
Epoch [14000/30000], Loss: 1261973.125000
Epoch [14100/30000], Loss: 1286331.875000
Epoch [14200/30000], Loss: 1257292.750000
Epoch [14300/30000], Loss: 1259631.875000
Epoch [14400/30000], Loss: 1303823.250000
Epoch [14500/30000], Loss: 1293542.625000
Epoch [14600/30000], Loss: 1291717.250000
Epoch [14700/30000], Loss: 1245042.250000
Epoch [14800/30000], Loss: 1304844.500000
Epoch [14900/30000], Loss: 1253638.500000
Epoch [15000/30000], Loss: 1238973.625000
Epoch [15100/30000], Loss: 1258649.625000
Epoch [15200/30000], Loss: 1301948.125000
Epoch [15300/30000], Loss: 1257170.125000
Epoch [15400/30000], Loss: 1281299.375000
Epoch [15500/30000], Loss: 1231588.375000
Epoch [15600/30000], Loss: 1266329.750000
Epoch [15700/30000], Loss: 1274902.625000
Epoch [15800/30000], Loss: 1294282.000000
Epoch [15900/30000], Loss: 1241814.250000
Epoch [16000/30000], Loss: 1265832.625000
Epoch [16100/30000], Loss: 1306121.250000
Epoch [16200/30000], Loss: 1252008.125000
Epoch [16300/30000], Loss: 1249090.125000
Epoch [16400/30000], Loss: 1241833.250000
Epoch [16500/30000], Loss: 1252764.125000
Epoch [16600/30000], Loss: 1219788.250000
Epoch [16700/30000], Loss: 1246995.625000
Epoch [16800/30000], Loss: 1274056.250000
Epoch [16900/30000], Loss: 1241773.875000
Epoch [17000/30000], Loss: 1224609.625000
Epoch [17100/30000], Loss: 1263795.500000
Epoch [17200/30000], Loss: 1267022.875000
Epoch [17300/30000], Loss: 1212998.750000
Epoch [17400/30000], Loss: 1276100.500000
Epoch [17500/30000], Loss: 1254571.125000
Epoch [17600/30000], Loss: 1228446.625000
Epoch [17700/30000], Loss: 1265691.750000
Epoch [17800/30000], Loss: 1292410.500000
Epoch [17900/30000], Loss: 1220388.000000
Epoch [18000/30000], Loss: 1265891.375000
Epoch [18100/30000], Loss: 1213529.750000
Epoch [18200/30000], Loss: 1218333.250000
Epoch [18300/30000], Loss: 1240758.750000
Epoch [18400/30000], Loss: 1273095.625000
Epoch [18500/30000], Loss: 1220010.000000
Epoch [18600/30000], Loss: 1250744.500000
Epoch [18700/30000], Loss: 1238768.750000
Epoch [18800/30000], Loss: 1212441.125000
Epoch [18900/30000], Loss: 1203826.125000
Epoch [19000/30000], Loss: 1248756.000000
Epoch [19100/30000], Loss: 1193677.375000
Epoch [19200/30000], Loss: 1202009.875000
Epoch [19300/30000], Loss: 1248585.750000
Epoch [19400/30000], Loss: 1192273.500000
Epoch [19500/30000], Loss: 1214579.875000
Epoch [19600/30000], Loss: 1209644.375000
Epoch [19700/30000], Loss: 1191845.125000
Epoch [19800/30000], Loss: 1256202.500000
Epoch [19900/30000], Loss: 1249244.500000
Epoch [20000/30000], Loss: 1183966.000000
Epoch [20100/30000], Loss: 1183147.250000
Epoch [20200/30000], Loss: 1234463.500000
Epoch [20300/30000], Loss: 1228083.250000
Epoch [20400/30000], Loss: 1226785.125000
Epoch [20500/30000], Loss: 1181394.875000
Epoch [20600/30000], Loss: 1208000.000000
Epoch [20700/30000], Loss: 1241393.750000
Epoch [20800/30000], Loss: 1184774.125000
Epoch [20900/30000], Loss: 1194441.625000
Epoch [21000/30000], Loss: 1236436.875000
Epoch [21100/30000], Loss: 1180027.000000
Epoch [21200/30000], Loss: 1185138.750000
Epoch [21300/30000], Loss: 1173460.250000
Epoch [21400/30000], Loss: 1194558.000000
Epoch [21500/30000], Loss: 1258263.875000
Epoch [21600/30000], Loss: 1176724.250000
Epoch [21700/30000], Loss: 1235544.250000
Epoch [21800/30000], Loss: 1177521.250000
Epoch [21900/30000], Loss: 1166224.750000
Epoch [22000/30000], Loss: 1209674.125000
Epoch [22100/30000], Loss: 1233599.375000
Epoch [22200/30000], Loss: 1164122.000000
Epoch [22300/30000], Loss: 1174929.500000
Epoch [22400/30000], Loss: 1169676.250000
Epoch [22500/30000], Loss: 1212807.625000
Epoch [22600/30000], Loss: 1269201.500000
Epoch [22700/30000], Loss: 1182448.750000
Epoch [22800/30000], Loss: 1225081.375000
Epoch [22900/30000], Loss: 1160685.500000
Epoch [23000/30000], Loss: 1170290.500000
Epoch [23100/30000], Loss: 1194583.750000
Epoch [23200/30000], Loss: 1194025.000000
Epoch [23300/30000], Loss: 1181899.250000
Epoch [23400/30000], Loss: 1170727.125000
Epoch [23500/30000], Loss: 1216004.500000
Epoch [23600/30000], Loss: 1228391.375000
Epoch [23700/30000], Loss: 1154531.625000
Epoch [23800/30000], Loss: 1210816.500000
Epoch [23900/30000], Loss: 1190062.750000
Epoch [24000/30000], Loss: 1170958.875000
Epoch [24100/30000], Loss: 1203632.750000
Epoch [24200/30000], Loss: 1201880.375000
Epoch [24300/30000], Loss: 1188267.375000
Epoch [24400/30000], Loss: 1164545.875000
Epoch [24500/30000], Loss: 1169809.125000
Epoch [24600/30000], Loss: 1145636.125000
Epoch [24700/30000], Loss: 1196445.625000
Epoch [24800/30000], Loss: 1149998.875000
Epoch [24900/30000], Loss: 1142740.875000
Epoch [25000/30000], Loss: 1163045.250000
Epoch [25100/30000], Loss: 1187737.875000
Epoch [25200/30000], Loss: 1197305.000000
Epoch [25300/30000], Loss: 1208913.750000
Epoch [25400/30000], Loss: 1158247.625000
Epoch [25500/30000], Loss: 1160197.125000
Epoch [25600/30000], Loss: 1133524.250000
Epoch [25700/30000], Loss: 1165428.875000
Epoch [25800/30000], Loss: 1152334.750000
Epoch [25900/30000], Loss: 1137282.000000
Epoch [26000/30000], Loss: 1145439.125000
Epoch [26100/30000], Loss: 1171921.750000
Epoch [26200/30000], Loss: 1151725.125000
Epoch [26300/30000], Loss: 1164252.750000
Epoch [26400/30000], Loss: 1150252.875000
Epoch [26500/30000], Loss: 1189179.000000
Epoch [26600/30000], Loss: 1182723.375000
Epoch [26700/30000], Loss: 1195505.125000
Epoch [26800/30000], Loss: 1162795.250000
Epoch [26900/30000], Loss: 1152005.250000
Epoch [27000/30000], Loss: 1128448.625000
Epoch [27100/30000], Loss: 1149500.750000
Epoch [27200/30000], Loss: 1119131.875000
Epoch [27300/30000], Loss: 1149352.625000
Epoch [27400/30000], Loss: 1138288.500000
Epoch [27500/30000], Loss: 1127890.375000
Epoch [27600/30000], Loss: 1120858.625000
Epoch [27700/30000], Loss: 1132132.625000
Epoch [27800/30000], Loss: 1173186.625000
Epoch [27900/30000], Loss: 1179414.750000
Epoch [28000/30000], Loss: 1124079.750000
Epoch [28100/30000], Loss: 1113660.625000
Epoch [28200/30000], Loss: 1113752.000000
Epoch [28300/30000], Loss: 1123318.875000
Epoch [28400/30000], Loss: 1118040.625000
Epoch [28500/30000], Loss: 1146297.000000
Epoch [28600/30000], Loss: 1153370.875000
Epoch [28700/30000], Loss: 1169065.625000
Epoch [28800/30000], Loss: 1180890.000000
Epoch [28900/30000], Loss: 1173793.750000
Epoch [29000/30000], Loss: 1162057.875000
Epoch [29100/30000], Loss: 1175239.750000
Epoch [29200/30000], Loss: 1129964.125000
Epoch [29300/30000], Loss: 1102701.500000
Epoch [29400/30000], Loss: 1123347.875000
Epoch [29500/30000], Loss: 1100926.375000
Epoch [29600/30000], Loss: 1103464.000000
Epoch [29700/30000], Loss: 1099781.625000
Epoch [29800/30000], Loss: 1105262.250000
Epoch [29900/30000], Loss: 1098491.750000
Epoch [30000/30000], Loss: 1117478.375000

In [61]:
model.eval()
y_pred=model(X_test_tensor).detach().numpy()

In [62]:
from sklearn.metrics import mean_squared_error,mean_absolute_error,r2_score

Y_test_numpy = Y_test_tensor.numpy()
# calculate metrics\
mse=mean_squared_error(Y_test_numpy, y_pred)
rmse = mse **0.5
mae=mean_absolute_error(Y_test_numpy, y_pred)
r2=r2_score(Y_test_numpy, y_pred)

print(f"MSE: {mse}")
print(f"RMSE: {rmse}")
print(f"MAE: {mae}")
print(f"R2_SCORE: {r2}")

MSE: 78849864.0
RMSE: 8879.74459092152
MAE: 6113.41064453125
R2_SCORE: 0.49210619926452637

In [70]:
def predict_charges(age, sex, bmi, children, smoker,region):
  input_data=pd.DataFrame([[age, sex, bmi, children, smoker, region]],
               columns=['age','sex','bmi','children','smoker','region'])

  for col in ['sex','smoker','region']:
    input_data[col]=label_encoder[col].transform(input_data[col])
  input_data=scaler.transform(input_data)
  input_tensor=torch.tensor(input_data, dtype= torch.float32)
  predicted_charge=model(input_tensor).item()
  return predicted_charge

In [73]:
predicted=predict_charges(62,'female',26.29,0,'yes','southeast')

In [74]:
predicted

28447.12109375